### ISSUE TITLE
Gallery Submission Feedback

### ISSUE THREAD

**Issue by fa653** [termsfeed/termsfeed-cookie-consent-gtm-community-template#1]
Provide a description of template functionality in for TermsFeed Cookie Consent's description

**Comment by termsfeed** [comment]
@fa653 Done.

**Comment by fa653** [comment]
@termsfeed Thank for you updating, but I was referring to the description in your template: https://github.com/termsfeed/termsfeed-cookie-consent-gtm-community-template/blob/9d03ce804db78efad5d60944ce3aabd576b1e831/template.tpl#L22

Here's the template style guide for reference: https://developers.google.com/tag-platform/tag-manager/templates/style?sjid=13546057612994004043-NC

**Comment by termsfeed** [comment]
@fa653 Ah, got it. Updated now.
Repo URL has been updated to mention the version we're using, resubmitted it again for Community Templates.

https://github.com/termsfeed/termsfeed-cookie-consent-4-1-gtm-community-template

**Comment by fa653** [comment]
@termsfeed Acknowledged. After reviewing the most recent submission, we have discovered the following: 

-  Provide a brief description of the template functionality in your template file's description: https://github.com/termsfeed/termsfeed-cookie-consent-4-1-gtm-community-template/blob/9d03ce804db78efad5d60944ce3aabd576b1e831/template.tpl#L22

- setDefaultConsentState was declared but not used if your template file: https://github.com/termsfeed/termsfeed-cookie-consent-4-1-gtm-community-template/blob/9d03ce804db78efad5d60944ce3aabd576b1e831/template.tpl#L101C7-L101C29. Was this intentional?

**Comment by termsfeed** [comment]
@fa653 

Thanks. We've updated this. My replies below:

> Provide a brief description of the template functionality in your template file's description:

I've updated the `description` field, see https://github.com/termsfeed/termsfeed-cookie-consent-4-1-gtm-community-template/blob/main/template.tpl#L26

Your comment here points to `9d03ce8` commit (initial release of template), but we've already updated the `description` field in `8912791` commit.

> setDefaultConsentState was declared but not used if your template file: https://github.com/termsfeed/termsfeed-cookie-consent-4-1-gtm-community-template/blob/9d03ce804db78efad5d60944ce3aabd576b1e831/template.tpl#L101C7-L101C29. Was this intentional?

Oops, just a mistake from our end. Removed it now in `dfc2847 ` commit, we're not using it.

**Comment by termsfeed** [comment]
@fa653 Is there a specific timeline when the Template page is updated with the latest repository changes we've published? As the current Template I see published is the old one without a proper `description`.

**Comment by fa653** [comment]
@termsfeed I apologize for the delay. The pull request for this was marked approved but did not go through because of the following reason:
- To make the template changes live you need to update your metadata.yaml file to point to the latest commit with the template changes.

After. your metadata.yaml file is updated, we can continue the approval process.

**Comment by termsfeed** [comment]
@fa653 Ah, got it, we've missed that. Updated now. Thanks!
